[project]
name = "chameleon"
version = "0.1.0"
description = "An all-purpose, do-anything library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.82.0",
    "requests>=2.32.3",
]
